In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv("customer_churn_cleaned.csv")

In [8]:
df.head()

df.shape

df.info()

df.describe()

df["Churn"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [9]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for column in X.columns:
    if X[column].dtype == "object":
        X[column] = le.fit_transform(X[column])

y = le.fit_transform(y)

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [14]:
y_pred = model.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8147622427253371


In [16]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[940  96]
 [165 208]]


In [17]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88      1036
           1       0.68      0.56      0.61       373

    accuracy                           0.81      1409
   macro avg       0.77      0.73      0.75      1409
weighted avg       0.81      0.81      0.81      1409



In [18]:
from sklearn.metrics import roc_auc_score

roc = roc_auc_score(y_test, y_pred)

print("ROC-AUC Score:", roc)

ROC-AUC Score: 0.7324883290030743


In [19]:
from sklearn.tree import DecisionTreeClassifier

In [39]:
dt_model = DecisionTreeClassifier(random_state=42)

In [40]:
dt_model.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [41]:
y_pred_dt = dt_model.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score

accuracy_dt = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", accuracy_dt)

Decision Tree Accuracy: 0.7175301632363378


In [43]:
from sklearn.metrics import confusion_matrix

cm_dt = confusion_matrix(y_test, y_pred_dt)

print(cm_dt)

[[834 202]
 [196 177]]


In [29]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.87      0.86      0.86      1036
           1       0.61      0.64      0.62       373

    accuracy                           0.80      1409
   macro avg       0.74      0.75      0.74      1409
weighted avg       0.80      0.80      0.80      1409



In [30]:
from sklearn.metrics import roc_auc_score

roc_dt = roc_auc_score(y_test, y_pred_dt)

print("Decision Tree ROC-AUC:", roc_dt)

Decision Tree ROC-AUC: 0.7457831730619935


In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
knn_model = KNeighborsClassifier(n_neighbors=5)

In [33]:
knn_model.fit(X_train, y_train)

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [34]:
y_pred_knn = knn_model.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score

accuracy_knn = accuracy_score(y_test, y_pred_knn)

print("KNN Accuracy:", accuracy_knn)

KNN Accuracy: 0.772888573456352


In [36]:
from sklearn.metrics import confusion_matrix

cm_knn = confusion_matrix(y_test, y_pred_knn)

print(cm_knn)

[[899 137]
 [183 190]]


In [37]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.83      0.87      0.85      1036
           1       0.58      0.51      0.54       373

    accuracy                           0.77      1409
   macro avg       0.71      0.69      0.70      1409
weighted avg       0.76      0.77      0.77      1409



In [38]:
from sklearn.metrics import roc_auc_score

roc_knn = roc_auc_score(y_test, y_pred_knn)

print("KNN ROC-AUC:", roc_knn)

KNN ROC-AUC: 0.6885719978883518


In [44]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
rf_model = RandomForestClassifier(random_state=42)

In [46]:
rf_model.fit(X_train, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [47]:
y_pred_rf = rf_model.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score

accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy:", accuracy_rf)

Random Forest Accuracy: 0.7970191625266146


In [49]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred_rf))

[[943  93]
 [193 180]]


In [50]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1036
           1       0.66      0.48      0.56       373

    accuracy                           0.80      1409
   macro avg       0.74      0.70      0.71      1409
weighted avg       0.78      0.80      0.79      1409



In [51]:
from sklearn.metrics import roc_auc_score

roc_rf = roc_auc_score(y_test, y_pred_rf)

print("Random Forest ROC-AUC:", roc_rf)

Random Forest ROC-AUC: 0.6964026933866075


In [52]:
from sklearn.naive_bayes import GaussianNB

In [53]:
nb_model = GaussianNB()

In [54]:
nb_model.fit(X_train, y_train)

,priors,None
,var_smoothing,1e-09


In [55]:
y_pred_nb = nb_model.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score

accuracy_nb = accuracy_score(y_test, y_pred_nb)

print("Naive Bayes Accuracy:", accuracy_nb)

Naive Bayes Accuracy: 0.759403832505323


In [57]:
from sklearn.metrics import confusion_matrix

cm_nb = confusion_matrix(y_test, y_pred_nb)

print(cm_nb)

[[782 254]
 [ 85 288]]


In [58]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_nb))

              precision    recall  f1-score   support

           0       0.90      0.75      0.82      1036
           1       0.53      0.77      0.63       373

    accuracy                           0.76      1409
   macro avg       0.72      0.76      0.73      1409
weighted avg       0.80      0.76      0.77      1409



In [59]:
from sklearn.metrics import roc_auc_score

roc_nb = roc_auc_score(y_test, y_pred_nb)

print("Naive Bayes ROC-AUC:", roc_nb)

Naive Bayes ROC-AUC: 0.7634721086463713


In [60]:
from sklearn.svm import SVC

In [61]:
svm_model = SVC(random_state=42)

In [62]:
svm_model.fit(X_train, y_train)

,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [63]:
y_pred_svm = svm_model.predict(X_test)

In [64]:
from sklearn.metrics import accuracy_score

accuracy_svm = accuracy_score(y_test, y_pred_svm)

print("SVM Accuracy:", accuracy_svm)

SVM Accuracy: 0.7991483321504613


In [65]:
from sklearn.metrics import confusion_matrix

cm_svm = confusion_matrix(y_test, y_pred_svm)

print(cm_svm)

[[948  88]
 [195 178]]


In [66]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.83      0.92      0.87      1036
           1       0.67      0.48      0.56       373

    accuracy                           0.80      1409
   macro avg       0.75      0.70      0.71      1409
weighted avg       0.79      0.80      0.79      1409



In [67]:
from sklearn.metrics import roc_auc_score

roc_svm = roc_auc_score(y_test, y_pred_svm)

print("SVM ROC-AUC:", roc_svm)

SVM ROC-AUC: 0.6961348556522818


In [68]:
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "KNN",
        "Random Forest",
        "Naive Bayes",
        "SVM"
    ],
    "Accuracy": [
        accuracy,
        accuracy_dt,
        accuracy_knn,
        accuracy_rf,
        accuracy_nb,
        accuracy_svm
    ],
    "ROC-AUC": [
        roc,
        roc_dt,
        roc_knn,
        roc_rf,
        roc_nb,
        roc_svm
    ]
})

print(results)

                 Model  Accuracy   ROC-AUC
0  Logistic Regression  0.814762  0.732488
1        Decision Tree  0.717530  0.745783
2                  KNN  0.772889  0.688572
3        Random Forest  0.797019  0.696403
4          Naive Bayes  0.759404  0.763472
5                  SVM  0.799148  0.696135


In [69]:
best_model = results.loc[results["Accuracy"].idxmax()]

print(best_model)

Model       Logistic Regression
Accuracy               0.814762
ROC-AUC                0.732488
Name: 0, dtype: object


In [70]:
import joblib

joblib.dump(model, "customer_churn_model.pkl")

['customer_churn_model.pkl']

In [71]:
loaded_model = joblib.load("customer_churn_model.pkl")

In [73]:
new_customer = X_test[0].reshape(1, -1)

In [74]:
prediction = loaded_model.predict(new_customer)

print(prediction)

[1]
